import { NextResponse } from "next/server";
import { Redis } from "@upstash/redis";

const redis = Redis.fromEnv();

export const maxDuration = 60;

export async function POST(req: Request) {
  const anthropicKey = process.env.ANTHROPIC_API_KEY;
  const resendKey    = process.env.RESEND_API_KEY;
  if (!anthropicKey || !resendKey) return NextResponse.json({ error: "Missing API keys" }, { status: 500 });

  // ── 读取 Meltwater 数据 ──────────────────────────────────
  let mwSummary = "No Meltwater data uploaded yet.";
  let journalists: any[] = [];
  try {
    const mwRaw = await redis.get("meltwater") as string | null;
    if (mwRaw) {
      const mw    = typeof mwRaw === "string" ? JSON.parse(mwRaw) : mwRaw;
      const rows: any[] = mw.rows || [];
      const date: string = mw.date || "";
      const tier1 = rows.filter((r: any) => (r.reach || 0) >= 1000000);
      const pos   = rows.filter((r: any) => (r.sentiment || "").includes("pos")).length;
      const neg   = rows.filter((r: any) => (r.sentiment || "").includes("neg")).length;
      const outlets = [...new Set(tier1.map((r: any) => r.outlet).filter(Boolean))].slice(0, 8).join(", ");

      // 提取记者信息
      journalists = tier1
        .filter((r: any) => r.author && r.author !== "Staff" && r.author !== "")
        .slice(0, 6)
        .map((r: any) => ({ name: r.author, outlet: r.outlet, title: r.title, url: r.url, sentiment: r.sentiment }));

      mwSummary = `Data from ${date}:
- Total mentions: ${rows.length}
- Tier 1 articles (Reach >1M): ${tier1.length}
- Positive: ${pos}, Negative: ${neg}, Neutral: ${rows.length - pos - neg}
- Tier 1 outlets: ${outlets}
- Top Tier 1 articles:
${tier1.slice(0, 5).map((r: any) => `  • "${r.title}" — ${r.outlet} (Reach: ${Number(r.reach).toLocaleString()}, ${r.sentiment})`).join("\n")}`;
    }
  } catch {}

  // ── 生成周报 + Pitch 草稿 ────────────────────────────────
  const journalistList = journalists.length > 0
    ? journalists.map(j => `- ${j.name} (${j.outlet}): wrote "${j.title?.slice(0, 80)}" — sentiment: ${j.sentiment}`).join("\n")
    : "No journalists identified from this week's data.";

  const today = new Date().toLocaleDateString("en-US", { weekday:"long", month:"long", day:"numeric", year:"numeric" });

  const prompt = `Today is ${today}. You are a senior PR strategist writing a weekly report for Plaud AI's Brand Director and CMO.

MELTWATER DATA THIS WEEK:
${mwSummary}

JOURNALISTS WHO COVERED PLAUD THIS WEEK:
${journalistList}

Write a professional weekly PR report email. Include:

1. WEEKLY PERFORMANCE SUMMARY (3-4 sentences, factual, based on real data above)

2. KEY HIGHLIGHTS (3-4 bullet points of the most important coverage or trends)

3. NEXT WEEK ACTION PLAN (5 specific, actionable items the PR team should do next week)

4. JOURNALIST FOLLOW-UP PITCHES
For each journalist who covered Plaud, write a short follow-up pitch email draft (3-4 sentences each). The pitch should:
- Reference their specific article
- Offer an exclusive angle or additional story
- Be warm but professional

Format the output as HTML email content with clear sections. Use <h2> for section headers, <ul> for lists, <p> for paragraphs. Keep it clean and professional. No fluff.`;

  let emailHtml = "";
  try {
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type":      "application/json",
        "x-api-key":         anthropicKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model:      "claude-sonnet-4-20250514",
        max_tokens: 2000,
        system:     "You are a senior PR strategist for Plaud AI. Write professional, concise PR reports in HTML format.",
        messages:   [{ role: "user", content: prompt }],
      }),
    });
    const data = await res.json();
    emailHtml  = data.content?.find((b: any) => b.type === "text")?.text || "";
  } catch (e: any) {
    return NextResponse.json({ error: `Claude error: ${e.message}` }, { status: 500 });
  }

  // ── 发送邮件 ─────────────────────────────────────────────
  const fullHtml = `
    <div style="font-family: Arial, sans-serif; max-width: 700px; margin: 0 auto; color: #1a1a2e;">
      <div style="background: linear-gradient(135deg, #6366f1, #22d3ee); padding: 24px 32px; border-radius: 8px 8px 0 0;">
        <h1 style="color: #fff; margin: 0; font-size: 20px;">Plaud PR Weekly Report</h1>
        <p style="color: rgba(255,255,255,0.8); margin: 4px 0 0; font-size: 13px;">${today}</p>
      </div>
      <div style="padding: 32px; background: #f8f9ff; border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 8px 8px;">
        ${emailHtml}
      </div>
      <p style="text-align: center; color: #94a3b8; font-size: 11px; margin-top: 16px;">
        Generated by Plaud PR Intelligence Dashboard · <a href="https://plaud-dashboard.vercel.app" style="color: #6366f1;">View Dashboard</a>
      </p>
    </div>
  `;

  try {
    const sendRes = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type":  "application/json",
        "Authorization": `Bearer ${resendKey}`,
      },
      body: JSON.stringify({
        from: "Plaud PR Dashboard <onboarding@resend.dev>",
        to:      ["elina@plaud.ai"],
        subject: `📊 Plaud PR Weekly Report — ${today}`,
        html:    fullHtml,
      }),
    });
    const sendData = await sendRes.json();
    if (!sendRes.ok) return NextResponse.json({ error: sendData }, { status: 500 });
    return NextResponse.json({ ok: true, id: sendData.id });
  } catch (e: any) {
    return NextResponse.json({ error: `Resend error: ${e.message}` }, { status: 500 });
  }
}